<?php 
$tableParams = array(
	'tableId' 			=> 'wp-theme-table',
    'tableWidth'        => '4',
);

echo $this->zrayTable($tableParams); //zrayTableHtml 
?>

<script type="text/javascript">
(function() {
	var storage = zray.getStorage('theme');

	// create main table
	var maintable = zray.createTable(storage, jQuery('#<?php echo $tableParams['tableId']; ?>'));
	var cols = [
		{
			"label": "Theme",
			"propertyName": "name",
			"sortable": true,
			"width": '20%'
		},
		{
			"label": "Duration Inclusive (ms)",
			"propertyName": "dInclusive",
			"sortable": true,
			"width": '20%'
		},
		{
			"label": "Duration Exclusive (ms)",
			"propertyName": "dExclusive",
			"sortable": true,
			"width": '20%'
		}
		
	];
	
	if(zray.getFileActions && zray.showInIde){
		cols.push({
			label: 'File Name',
			tooltip: 'File actions',
			propertyName: 'filename',
			sortable:true,
			getHtml: function(val, rec) {
				var showInIDEParams = {filePath: rec.filename, line: rec.line, fullUrl: document.location.href};
				return zray.getFileActions(rec.fileLine, val, rec.filename, showInIDEParams);
			}
		});
	}else{
		cols.push({
			"label": "File Name",
			"propertyName": "fileLine",
			"sortable": true,
			"width": '20%'
		});
	}
	
	maintable.setColumns(cols);
	// create main table - end
	var template = {};
	zray.registerDataHandler('WordPress', 'generalInfo', function(generalInfoData, requestData) {
		zendDevBar.showData('functions');
		jQuery.each(generalInfoData,function(k,v){
			if (typeof v.name == "undefined") {
				return;
			}
			switch(v.name.toLowerCase()){
				case 'template':
					template.name = v.value;
					break;
				case 'template directory':
					template.dir = v.value;
					break;
			}
		});
		loadProfilingData(template);
		
	});
	
	var loadingProfilingData = false;
	var loadProfilingData = function(template){
		if(loadingProfilingData) { return; }
		var functionsData = zendDevBar.getStorage('functions').getData();
		if(functionsData.length == 0){
		return setTimeout(function(){ 
				loadProfilingData(template);
			},100);
		}
		loadingProfilingData = true;
		
		var funcs = [];
		
		jQuery.each(functionsData,function(fIndex,functionData){
			var filename = functionData.filename.replace(/\\/g,'/');
			if(filename.indexOf(template.dir) == 0){
				var item = {
					filename: functionData.filename,
					line: functionData.line,
					name: functionData.functionFull,
					dInclusive: functionData.timeInclusive / 1000,
					dExclusive: functionData.timeExclusive / 1000,
					fileLine: template.name + filename.replace(template.dir,'')+':'+functionData.line
				};
				funcs.push(item);
			}
		});
		storage.setData(funcs);
		jQuery('[data-name="zrayExtension:wordpress/plugins"] .zdb-toolbar-info').append(' ('+funcs.length+')');
	}
	
	
})();
</script>
